### ISSUE TITLE
[스터디] Observer

### ISSUE THREAD

**Issue by godrm** [codesquad-members-2024/swift-todo#1]
`Observer` 특정한 값 변화를 관찰하는 방식으로 여러가지 방식이 있습니다. 관련이 있거나 비슷한 것을 다양한 관점에서 스터디해보고 정리해보세요
적어도 어떤 환경에서 어떤 맥락으로 사용하는 것인지 찾아보고, 예제 코드도 한 번씩 살펴보세요. 
완벽하게 이해해야 한다기 종합적으로 이해하고 시야를 넓히는 것이 우선입니다 
- Observer Pattern
- Publisher-Subsciber Pattern
- KVO (Key-Value Observing)
- NotificationCenter 
- Combine 프레임워크
- Observable 개념 
- Observation 프레임워크

**Comment by joho2022** [comment]
**Static Dispatch : 컴파일 시점에 메소드호출이 결정되는 방식, final 메서드 생각하기**

**Dynamic Dispatch : 런타임 시점에 어떤 메소드를 호출할지 결정하는 방식, 오버라이드 메소드 생각하기**

# 옵저버 패턴

관찰 중인 객체에서 발생하는 이벤트를 여러 다른 객체에 알리는 메커니즘

- 객체 간의 일대다 의존관계를 정의
- 주체와 옵저버 사이의 결합도를 낮추고, 유연한 코드 작성 가능

언제사용🤔? 관찰 중인 객체의 상태가 변경될 때마다 행동, 업데이트를 처리하고 싶을 때 옵저버 패턴을 사용한다.

## Observation 프레임워크

### NotificationCenter

NotificationCenter에 등록된 event가 발생하면 해당 event에 대한 행동을 취한다.

```swift
var name: Notification.Name // 알림을 식별하는 태그
var object: Any? // 발송자가 옵저버에게 보내려고 하는 객체. 주로 발송자 객체를 전달하는 데 쓰임
var userInfo: [AnyHashable : Any]? // Notification과 관련된 값 또는 객체의 저장소
//----
// .post는 알림을 식별하는 태그(옵저버)에게 일을 수행하라고 시킴.
NotificationCenter.default.post(name: NSNotification.Name("TestNotification"), object: nil, userInfo: nil)
//----
 // 옵저버 등록
 NotificationCenter.default.addObserver(self, selector: #selector(didRecieveTestNotification(_:)), name: NSNotification.Name("TestNotification"), object: nil)

 @objc func didRecieveTestNotification(_ notification: Notification) {
         print("Test Notification")
 }
//----
// 익스텐션으로 property 추가 
extension Notification.Name {
    static let doItSomeThing = Notification.Name("doItSomeThing")
}
//----
// post 값 전달하기
// 오브젝트 부분에 String값을 넣어서 post해줌
NotificationCenter.default.post(name: .testnoti, object: "testobject")
//---- 옵저버에서 ..
@objc func getValue(_ notification: Notification){
	let getValue = notification.object as! String
	print(getValue)
}
```

### KVO (Key Value Observing)

NSObject를 상속해야 하고, class에서만 사용이 가능( 순수 스위프트 코드 작성이 어렵다)

observe하려는 프로퍼티에 `@objc attribute` 와 `dynamic modifier`  추가해야 함.

`dynamic modifier` 이 선언된 부분에 한해 Objective-C 런타임 방식을 사용하겠다는 것이고, 런타임 시점에 호출해야 할 특정 메소드의 구현을 결정하는 것

언제사용🤔? 외부 라이브러리에 내부 소스를 변경할 수 없으니, 값 변화를 KVO 방식을 사용해서 관찰할 때 사용한다.

[단점]

1. Objective-C 런타임에 의존 및 클래스만 구현 가능(NSObject 상속)
2. dealloc될 때 옵저버를 지워줘야 한다.

```swift
class Example: NSObject {
    @objc dynamic var value: Int = 0
}

let example = Example()

var observation: NSKeyValueObservation? = example.observe(\.value, options: [.old, .new]) { object, change in
    print("Value changed from \(change.oldValue!) to \(change.newValue!)")
}

example.value = 10
// Value changed from 0 to 10

// ----
// .inital
var observation: NSKeyValueObservation? = example.observe(\.value, options: [.old, .new, .initial]) { object, change in
    print("Value changed from \(change.oldValue) to \(change.newValue)")
}
// Value changed from nil to Optional(0)

// ----
// .prior
var observation: NSKeyValueObservation? = example.observe(\.value, options: [.old, .new, .prior]) { object, change in
    print("Value changed from \(change.oldValue) to \(change.newValue)")
}
Value changed from Optional(0) to nil
Value changed from Optional(0) to Optional(10)
```

- old : 변경전 값
- new : 변경 후 값
- initial: 등록 전 호출 시 newValue
- prior: 변경 전, 후 상태 표시

### Combine( Publisher-Subsciber Pattern )

Apple에서 직접 만든 Reactive 프로그래밍을 위한 프레임워크

iOS 13이상 버전부터 사용가능하며, Rx와 다르게 패키지를 받는 것이 아닌, 자체적으로 내장된 프레임워크이기 때문에 시간이나 메모리 할당 면에서 성능이 우수함.

SwiftUI와 UI바인딩을 하도록 설계.

### 왜 Combine이 소개되었는가?

- 왜?
    - 효율적인 비동기 처리
        - 기존의 비동기 처리 방식들
            - Target / Action
            - Notification Center
            - URLSession
            - KVO
            - Ad-hoc callbacks
        - 여러 방식들을 조합해서 개발하다보니, 코드도 복잡
        - 통합된 비동기 처리 방식이 필요
- 일관된 방식으로 비동기 처리 할수 있는 API 를 combine으로 제공
    - A unified, declarative API for processing values over time

# Combine Overview

- 3가지 주요 컴퍼넌트
    - Publisher
        - 이런 단어가 어울림: **생산자, 배출자, 크리에이터, 배설자**
    - Subscriber
        - 이런 단어가 어울림: **소비자, 구독자, 받는 사람**
    - Operator
        - 이런 단어가 어울림: **변경시키는 사람, 마법사, 가공 하는 사람**
